spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_fiscal
    username: fiscal
    password: fiscal
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: minha-chave-jwt-super-segura-com-mais-de-32-bytes-123456
  expiration: 86400000